services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c-next-portfolio
    ports:
      - '3030:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
  